[package]
name = "search_index"
version = "0.1.0"
authors = ["Cliff Crosland <cliffcrosland@gmail.com>"]

[dependencies]
rand = "0.5.5"
serde_json = "1.0"
unicode-segmentation = "1.2.1"

[features]
benchmarks = []
